### PR TITLE
Testing and updating

### PR DESCRIPTION
**Pull request by moxiegirl**
Updating with latest
Removing changes made to compose

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
@SvenDowideit give this an eye if you have a chance.

**Comment by SvenDowideit** [comment]
I'm not groking what you mean by compose changes - I see the change to the distribution project's branch names, and a pile of ssed's being replaced with sed's

I'm going to presume that there's a file missing?

**Comment by moxiegirl** [comment]
I replaced the seds because I was anticipating implementing my solution for the Markdown issue.

**Comment by SvenDowideit** [comment]
ah, ok, the sed's are the compose change

LGTM

**Pull request merged**
