### PR TITLE
Rebase hugo GitHub linking

### PR DESCRIPTION
**Pull request by SvenDowideit**
replaces #59 

and should be merged after testing.

this requires docker-compose 1.5

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@moxiegirl can we please merge this?

its a rebased version of `hugo-github-linking` plus some more fixes.

**Comment by moxiegirl** [comment]
@SvenDowideit testing

**Comment by moxiegirl** [comment]
@SvenDowideit I'm not able to do build-images.  I keep getting:

''''
Get:173 http://httpredir.debian.org/debian/ jessie/main rename all 0.20-3 [12.4 kB]
Get:174 http://httpredir.debian.org/debian/ jessie/main shared-mime-info amd64 1.3-1 [634 kB]
Get:175 http://httpredir.debian.org/debian/ jessie/main xml-core all 0.13+nmu2 [24.2 kB]
Fetched 111 MB in 53s (2077 kB/s)
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/liba/libalgorithm-merge-perl/libalgorithm-merge-perl_0.08-2_all.deb  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get update 	&& apt-get install -y 		gettext 		git 		libssl-dev 		make 		python-dev 		python-pippython-setuptools 		vim-tiny 		s3cmd 	&& apt-get clean 	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100
make: *** [build-images] Error 1
'''

**Comment by moxiegirl** [comment]
@SvenDowideit Can you please to fix that first `RUN` so it works on Mac.

**Comment by SvenDowideit** [comment]
@moxiegirl done.

I get these apt fetch issues intermittently on all platforms, including hub.

**Comment by moxiegirl** [comment]
@SvenDowideit Yeah...I did it a few times just to be sure it wasn't the fetch issue. As soon I as I removed the `\` no problem.  Go figure,

**Comment by moxiegirl** [comment]
Ugh...13 commits.  Next time I'll check for the rebase.

**Pull request merged**
