### PR TITLE
Docker 1.9.0 release Hugo GitHub linking

### PR DESCRIPTION
**Pull request by SvenDowideit**
This branch (`hugo-github-linking` the `docker/docs.docker.com` repo) is being used for building updates to the 1.9.0 related releases, so should not be updated with further changes.

I'm going to rebase in a new branch.

(keeping open for now, so I can see what the differences are)

this requires docker-compose 1.4.2

### CODE REVIEW

**Comment by SvenDowideit** [comment]
This branch (`hugo-github-linking` the `docker/docs.docker.com` repo) is being used for building updates to the 1.9.0 related releases, so should not be updated with further changes.

I'm going to rebase in a new branch.

**Comment by thaJeztah** [comment]
I think this can be closed because https://github.com/docker/docs.docker.com/issues/67 replaces this?

**Comment by SvenDowideit** [comment]
I'm keeping it so that @moxiegirl and I have some visibility into this branch, as its being used to publishing updates atm (if we close it, GH stops updating the PR when the branch is modified)

@moxiegirl `Attempt to fix the hugo alias based redirects when publishing to s3 …	e0e5fbe` should fix the hugo alias redirect to `localhost` or `192.....` issue. I'm testing it right now using our private jenkins builds.

**Comment by moxiegirl** [comment]
Hi @SvenDowideit my test it isn't working...I built on my S3 bucket 

```
<!DOCTYPE html><html><head><link rel="canonical" href="http://localhost/compose/compose-file/"/><meta http-equiv="content-type" content="text/html; charset=utf-8" /><meta http-equiv="refresh" content="0;url=http://localhost/compose/compose-file/" /></head></html>
```

Is what I am getting.

**Comment by SvenDowideit** [comment]
roger, will go get my mac running and see if its osx/machine related

**Comment by SvenDowideit** [comment]
ok, 1.9 has been released a few times, and its 'working' - so closing.

**Pull request closed without merging**
