### PR TITLE
1.9 redirects

### PR DESCRIPTION
**Pull request by SvenDowideit**
it seems we're limited to 50 redirects :(

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@moxiegirl @thajeztah

can you test a little using

http://svendowideit2.s3-website-us-east-1.amazonaws.com/

off to pick up the kids, back in a bit.

**Comment by thaJeztah** [comment]
Tested some redirects and they seem to work, so LGTM

Perhaps we should create a "smart" 404 to work around the 50 redirects limit, i.e. read out the URL on the 404 page and add a "were you looking for..." suggestion if it's a known URL without a redirect?

**Comment by SvenDowideit** [comment]
yup, I wrote that with a js based search index for the previous iteration of the docs - I think we'll get something like that working when the new theme adds the google search.

**Comment by moxiegirl** [comment]
Thanks @SvenDowideit huge help as you taking this on allowed me to finish an installation on Azure  for TP4.  LGTM

**Pull request merged**
